
class BoilerError(Exception):
    """ The base for errors generated by flask-boiler.
    """
    pass


class PropertyEvalError(BoilerError):
    """ An error generated when getting a property from an instance
            of a model.
    """
    pass


class UnauthorizedError(BoilerError):
    pass
