from flasgger import SwaggerView
from flask import jsonify
from .view_model import ViewModel
from google.cloud import firestore


def register_view_model(app, view_model_cls, mapper, description=None):
    """ Registers a view model as a REST API resource and generate
            corresponding documentation.

    :param app: flask app instance
    :param view_model_cls: class of view model
    :param mapper: function which receives kwargs from REST endpoint and
                    returns a firestore document reference
    :param description: description of the REST API resource for generating
                    flasgger documentations
    :return:
    """


    # Note that there are better ways of implementing this
    _proxy_view_cls_name = "{}ProxyView".format(view_model_cls.__name__)

    if description is None:
        description = "A REST API resource automatically generated by" \
                      " flask-boiler"

    responses = {
        200: {
            "description": description,
            "schema": view_model_cls.get_schema_cls()
        }
    }

    parameters = [
        {
            "name": "doc_id",
            "in": "path",
            "type": "string",
            "enum": ["all", "palette_id_a",
                     "palette_id_b"],
            "required": True,
            "default": "all"
        }
    ]

    def get(self, **kwargs):
        doc_ref: firestore.DocumentReference = mapper(kwargs)

        obj = self._view_model_cls.get(doc_ref)
        return jsonify(obj.to_dict())

    # Dynamically construct a proxy class that has responses static var
    proxy_view_cls = type(_proxy_view_cls_name,  # class name
                          (SwaggerView,),
                          dict(responses=responses,
                               parameters=parameters,
                               _view_model_cls=view_model_cls,
                               get=get
                               )
                          )

    app.add_url_rule(
        '/palettes/<doc_id>',
        view_func=proxy_view_cls.as_view('colors'),
        methods=['GET']
    )


class GenericView(SwaggerView):

    _view_model_cls = None
    # responses = dict()

    def __new__(cls, view_model_cls: ViewModel=None, description=None, *args, **kwargs):
        """
        TODO: test
        Note that this implementation is unstable.

        :param view_model_cls:
        :param args:
        :param kwargs:
        :return:
        """

        instance = super().__new__(cls)

        cls._view_model_cls = view_model_cls

        # cls.responses = {
        #     200: {
        #         "description": str() if description is None else description,
        #         "schema": cls._view_model_cls.schema_cls
        #     }
        # }

        return instance

    def get(self, dev_path):

        doc_ref: firestore.DocumentReference = \
            firestore.DocumentReference(dev_path)

        assert callable(self._view_model_cls)

        view_model_obj = self._view_model_cls(doc_ref=doc_ref)

        assert isinstance(view_model_obj, ViewModel)

        return view_model_obj.to_dict()
